In [2]:
!pip install numpy



   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.6 MB 3.6 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.6 MB 3.7 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.6 MB 3.7 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.6 MB 3.9 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.6 MB 3.8 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.6 MB 4.0 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.6 MB 4.3 MB/s eta 0:00:02
   ------------------------- -------------- 8.1/12.6 MB 4.5 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 4.6 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 4.8 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 4.9 MB/s eta 0:00:01
   --------

In [3]:
import numpy as np

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [9]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(0, 10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

## Multidimensional Arrays

In [21]:
np.zeros((5,2))


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
m = np.array([
    [1,2,3],
    [4,5,6]
])

In [23]:
m

array([[1, 2, 3],
       [4, 5, 6]])

Suppose we want to print only 2nd column

In [24]:
m[:,1]

array([2, 5])

In [25]:
m[1,2]

np.int64(6)

In [26]:
m


array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
m[1,:]

array([4, 5, 6])

In [29]:
m[1,1:]

array([5, 6])

## randomly Generated Arrays

In [30]:
np.random.rand(5,2)

array([[0.80393975, 0.04392057],
       [0.25697623, 0.93087334],
       [0.18053384, 0.74998498],
       [0.0320777 , 0.12076576],
       [0.27792578, 0.56695146]])

In [31]:
np.random.rand(5,2)

array([[0.56388709, 0.29425916],
       [0.50140417, 0.35879743],
       [0.72094446, 0.83299552],
       [0.43022561, 0.71058511],
       [0.58211739, 0.56681926]])

In [32]:
np.random.seed(5)
np.random.rand(5,2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [33]:
np.random.seed(5)
np.random.rand(5,2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

Basically rand is a pseudo random number generator, once we use the seed function, then the random numbers get repeated

In [34]:
np.random.seed(5)
np.random.randn(5,2)    #for standard normal distribution

array([[ 0.44122749, -0.33087015],
       [ 2.43077119, -0.25209213],
       [ 0.10960984,  1.58248112],
       [-0.9092324 , -0.59163666],
       [ 0.18760323, -0.32986996]])

In [35]:
np.random.seed(5)
100*np.random.rand(5,2)

array([[22.19931711, 87.07323062],
       [20.67191553, 91.86109079],
       [48.84111888, 61.17438629],
       [76.59078565, 51.84179879],
       [29.68005016, 18.77212287]])

In [36]:
np.random.seed(5)
np.random.randint(low=0, high=100,size=(5,2))

array([[99, 78],
       [61, 16],
       [73,  8],
       [62, 27],
       [30, 80]], dtype=int32)

# element wise operators

In [37]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a+1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
a= a **2

In [42]:
a

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [43]:
b = np.array([1,2,3,4,5,6,7,8,9])

In [44]:
a+b

array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])

# Comparison Operators

In [45]:
a > b

array([False,  True,  True,  True,  True,  True,  True,  True,  True])

In [46]:
a < 57

array([ True,  True,  True,  True,  True,  True,  True, False, False])

In [47]:
a

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [48]:
a[a>57]

array([64, 81])