Matrix Multiplication

In [3]:
import numpy as np

In [6]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

In [4]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [7]:
vector_vector_multiplication(u,v)

np.float64(110.0)

In [14]:
r = np.zeros((5,2))
r

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [16]:
M = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [1,0,0,0],
    
])

In [17]:
n = np.array([1,2,0,0])

In [26]:
matrix_vector_multiplication(M,n)

array([ 5., 17.,  1.])

In [28]:
M.dot(n)     ##built in function

array([ 5, 17,  1])

In [30]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [31]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Inverse

In [46]:
M = np.array([
    [1,2,3],
    [4,4,0],
    [0,0,9]
])

M

array([[1, 2, 3],
       [4, 4, 0],
       [0, 0, 9]])

In [47]:
M_inv=np.linalg.inv(M)

In [48]:
M_inv.dot(M)

array([[ 1.00000000e+00,  0.00000000e+00, -1.66533454e-16],
       [ 0.00000000e+00,  1.00000000e+00,  1.66533454e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])